version: "3.7"
services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - PRODUCTION=true
    deploy:
      restart_policy:
        condition: on-failure
