version: '3.7'
services:
  backend:
    build: ./backend
    ports:
      - "443:5000"
    volumes:
      - ./backend:/app
    command:
      "flask run -h 0.0.0.0"
  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    volumes:
      - ./frontend:/app
    command:
      "npm start"
