version: "3.7"
services:

  backend:
    image: ${CI_REGISTRY_IMAGE-registry.gitlab.com/vitalymegabyte/unknown_hack}/frontend:${TAG-latest}
    build: ./backend
    ports:
      - "5000:5000"
    volumes: 
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    deploy:
      restart_policy:
        condition: on-failure

  frontend:
    image: ${CI_REGISTRY_IMAGE-registry.gitlab.com/vitalymegabyte/unknown_hack}/backend:${TAG-latest}
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - /etc/letsencrypt/:/etc/nginx/ssl/:ro
    environment:
      - PRODUCTION=true
    deploy:
      restart_policy:
        condition: on-failure
